### ISSUE TITLE
Can't hear most announcer sounds

### ISSUE THREAD

**Issue by piotr25691** [Curilang/DDR-A3-THEME#1]
The announcer sounds in the theme do not play, what's wrong?
I have a DDR A announcer selected for the sounds not from the theme though.

Oh, and there is a typo in the Theme Options:
![image](https://user-images.githubusercontent.com/71488561/163706710-5e12a7e1-70ce-4c53-868a-94215a053095.png)

**Comment by Curilang** [comment]
You mean announcers like: "Select your Style, Select Options, Select Level, First Stage..."?
I erase those announcers because were a little noisy. Idk if it is an announcer that you downloaded for a site web because I use one of DDR SN and it works fine.

Oh, sorry for the "JUGGEMENT" lol, my bad. I'll fix it.

**Comment by piotr25691** [comment]
> You mean announcers like: "Select your Style, Select Options, Select Level, First Stage..."? I erase those announcers because were a little noisy. Idk if it is an announcer that you downloaded from a website because I use one of DDR SN and it works fine.
> 
> "JUGGEMENT" fixed. My bad lol

I see, however the files still exist in the theme.
Anyways I now should find the correct announcer for the theme.

**Comment by Curilang** [comment]
I know, follow the structure of these announcers and use those files if you want. 
https://zenius-i-vanisher.com/v5.2/thread?threadid=9822
Sorry if I disabled those announcers but it was a little annoying to hear the same announcer by the theme and announcer pack.

**Comment by piotr25691** [comment]
> I know, follow the structure of these announcers and use those files if you want. https://zenius-i-vanisher.com/v5.2/thread?threadid=9822 Sorry if I disabled those announcers but it was a little annoying to hear the same announcer by the theme and announcer pack.

I got those announcers, it's a bit better now however I still don't hear the stages announced and I don't know what should I do to get the announcer to announce the stage.
