### ISSUE TITLE
[OutFox] Left and right buttons change chart scroll speed

### ISSUE THREAD

**Issue by prototypicalpro** [Curilang/DDR-A3-THEME#14]
On OutFox the MenuLeft and MenuRight buttons are by default the same as the Left and Right buttons (I guess this is not the case in Stepmania). This theme binds the `CodeSpeedUp` and `CodeSpeedDown` to MenuLeft and MenuRight: while this works with Stepmania, in OutFox it causes the speed to change during gameplay. More info on a similar issue: https://github.com/TeamRizu/OutFox/issues/302.

From a code standpoint this may be not worth fixing, but I did want to share some workarounds in case anyone else runs into this issue (these are exclusive, choose one that works):
* Enable the "Dedicated Menu Buttons" option in OutFox and binding MenuLeft and MenuRight to a keyboard or controller.
* Comment out the following lines in `metrics.ini` of this theme. This will disable the binding that changes scroll speed.
https://github.com/Curilang/DDR-A3-THEME/blob/5cb975802391c5838654c62ab0f5a1e62ab54723/Themes/DDR%20A3/metrics.ini#L1968-L1969

**Comment by LimitBreaker98** [comment]
Just asking in case you know how to fix it... this theme has a bug where the options menu does not show up when holding/double tapping after selecting a song. 

Please LMK if there is any tip you may have regarding this :)

**Comment by LimitBreaker98** [comment]
Turns out the way to activate the options screen is just to press - or / on your keyboard.
