### ISSUE TITLE
Song titles clips into song catagory title

### ISSUE THREAD

**Issue by Tagischeap** [Curilang/DDR-A3-THEME#20]
When the amount of songs listed isn't a factor of three, The tile for the song(s) on the last row clips into the following song category tile under it.

**Comment by celunah** [comment]
> When the amount of songs listed isn't a factor of three, The tile for the song(s) on the last row clips into the following song category tile under it.

This is a bug with the DDR A song wheel, been here since the very first DDR A theme with it.
