### ISSUE TITLE
Game Crash: Access Violation

### ISSUE THREAD

**Issue by AegisPrincess** [Curilang/DDR-A3-THEME#23]
Just updated to the newest version of A3 and it was working fine until I went in and swapped options to turn off Event mode. Once i closed the game and restarted it up it would crash with the following crash reason as access violation. It would only run after trying a couple of times only to crash again. So not sure its a bug or something on my end. 
___
**StepMania5.1-UNKNOWN crash report (build UNKNOWN, 20230412 @ 08:55:00)**
--------------------------------------

Crash reason: Access Violation

Thread: Main thread
        RageFileDriverDirectHelpers.cpp:230 C:/Games/StepMania 5.1/Themes/DDR.A3/Other/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/StepMania 5.1/Save/UserPrefs/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/StepMania 5.1/Save/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/StepMania 5.1/Save/UserPrefs/DDR A3/*
        RageFileDriverDirectHelpers.cpp:230 C:/Games/StepMania 5.1/Save/UserPrefs/*
00007ff6f90ce881: StepMania!00007ff6f9000000

Static log:
StepMania5.1-UNKNOWN
Compiled 20230412 @ 08:55:00 (build UNKNOWN)
Log starting 2023-09-13 22:25:53
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 16293mb total, 18725mb swap (7673mb swap avail)
Video driver: NVIDIA GeForce RTX 3060 [NVIDIA]
              31.0.15.3623, 6-8-2023 [pci\ven_10de&dev_2504]
Drive: "NVMe    WD Blue SN570 1T00WD" Driver: stornvme DMA: N/A
Sound device 0: ASUS VP278 (NVIDIA High Definit, 10.0, MID 1, PID 100 
Sound device 1: FxSound Speakers (FxSound Audio, 10.0, MID 1, PID 100 
Sound device 2: Digital Audio (S/PDIF) (High De, 0.0, MID 1, PID 65535 
Sound device 3: VG248 (NVIDIA High Definition A, 10.0, MID 1, PID 100 
Language: en
Theme: DDR.A3

Partial log:
00:00.129: Loading "/Themes/DDR.A3/Scripts/05 Score.lua" ...
00:00.130: Loading "/Themes/DDR.A3/Scripts/06 ProfilePrefsHelpers.lua" ...
00:00.130: Loading "/Themes/DDR.A3/Scripts/06 SongAttributes.lua" ...
00:00.130: Loading "/Themes/DDR.A3/Scripts/07 DanceStages.lua" ...
00:00.130: Loading "/Themes/DDR.A3/Scripts/07 StagesManager.lua" ...
00:00.131: Loading "/Themes/DDR.A3/Scripts/ddr_groove_data.lua" ...
00:00.143: Loading "/Themes/DDR.A3/Scripts/SL - PlayerOptions.lua" ...
00:00.143: Loading "/Themes/DDR.A3/Scripts/XX ddr_groove_actor.lua" ...
00:00.144: Loading "/Themes/DDR.A3/Scripts/XX Gameplay.lua" ...
00:00.144: Loading "/Themes/DDR.A3/Scripts/XX StatsEngine.lua" ...

-- End of report

**Comment by Curilang** [comment]
I tried to do the same thing and nothing happened, try using ITGMania instead.

**Comment by piotr25691** [comment]
This crash also applies to ITGMania. Weird.

**Comment by celunah** [comment]
@Curilang I found the fix for this:

Update https://github.com/Curilang/DDR-A3-THEME/blob/main/ThemeInfo.ini#L6 to add a newline, at the end

The Lua runtime error "WARNING" can randomly cause the crash.
