### ISSUE TITLE
Dancestages cause crash when starting up song. ITGmania 0.7.0

### ISSUE THREAD

**Issue by makoflagkk** [Curilang/DDR-A3-THEME#24]
![DDR A3 Dancestages glitch](https://github.com/Curilang/DDR-A3-THEME/assets/130417801/3c1537f6-54e6-4309-9613-679e7942cf67)

Don't know why this happens. I tested it on the starlight theme and that theme does not make the game crash.  I have Windows 11 with AMD drivers. ASUS Rog Zephyrus G14. Processor AMD. Graphics Card AMD. I tried reinstalling drivers to see if that fixed the issue but it did not. Not really an issue for me since I only use the static backgrounds which make the game run better, but I thought I might as well address it.

**Comment by Curilang** [comment]
We said it before on ZiV thread, DanceStages is up to the creator, not for us
